name: transformer-hessian
channels:
  - anaconda
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=4.0.13  
  - numpy=1.26.4
  - python=3.10.14
  - pytorch=2.2.1
  - pytorch-lightning=2.2.2
  - scipy=1.12.0
  - pip:
      - curvlinops-for-pytorch==2.0.0
      - matplotlib==3.9.2
      - opencv-python==4.10.0.84
      - scikit-learn==1.5.2
      - tqdm==4.66.5
      - --editable ./transformer_lens/TransformerLens

